config/routes.rb
Rails.application.routes.draw do
  ## 提案する献立の表示＆レシピの表示  2016/10/03追加　井上
  get 'dish' => 'recipe_pages#result'
  get 'recipe/:id' => 'recipe_pages#recipe'
  get 'test' => 'recipe_pages#test'
  ## end

  get 'recipe/:id/fav' => 'recipe_pages#fav'

  get 'manu_disp/menu_disp'

  post 'question/menu_disp' => 'manu_pages#menu_disp'
  post 'question'=>'manu_pages#question'

  get 'init'=>'manu_pages#init'

  get 'question'=>'manu_pages#question'

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'user_pages#regist'

  get 'user_pages/:id' =>'user_pages#profile'

  get 'user_pages/:id/allergies' => 'user_pages#allergies'

  post 'user_pages/:id/allergies/allergiesinput' => 'user_pages#allergiesinput'

  get 'user_pages/:id/favdeleteselect' => 'user_pages#favdeleteselect'

  get 'user_pages/:id/favdeleteselect/favdelete' => 'user_pages#favdelete'

  get 'withdrawal' => 'user_pages#destroy'

  post 'signup/confirm' => 'user_pages#confirm'

  get 'about' =>'static_pages/about'

  root 'static_pages#home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :user_pages
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

end

app/controllers/user_pages_controller.rb
class UserPagesController < ApplicationController
  def regist
    @user = User.new
  end

  def profile
    @user = User.find_by(id: session[:user_id])
  end

  def edit
  end

  def login
  end

  def favdeleteselect
    @user = User.find(session[:user_id])
  end

  def favdelete
    @user = User.find(session[:user_id])
    favid = params[:favid]
    @favrecipe = Dish.find(favid)
    @user.dishes.destroy(@favrecipe)
    redirect_to :back
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    @user.destroy
  end

  def allergies
    @all = Allergy.all
    @user = User.find_by(id: session[:user_id])
  end

  def allergiesinput
#    params[:alle].inspect
#    len = params[:alle].length
#    @allstr = ""
#    i = 0
#    len.each do |all|
#      flg = false
#      if params[:alle][i].nil?
#      else
#        flg = true
#        @allstr.concat(params[:alle][i].to_s)
#        if i != len - 1 && flg
#            @allstr.concat(",")
#        end
#      end
#      i += 1
#    end
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if params[:back]
      render 'regist'
    elsif @user.save
      @user.send_activation_email
      flash[:info] = "入力されたメールアドレスにメールを送信しました。"
      redirect_to root_url
    else
      render 'regist'
    end
  end

  def confirm
    @user = User.new(user_params)
    render 'regist' if @user.invalid?
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
end

app/helpers/user_pages_helper.rb
module UserPagesHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/user_pages/allergies.html.erb
<div class="row">
<h1>アレルギー設定</h1>
  <p>該当するすべてのアレルギー食品にチェックを入れ、確定ボタンを押してください</p>
  <%= form_tag 'allergies/allergiesinput' do %>
    <% if @user.alvalue != nil %>
      <% checked = @user.alvalue.split(",") %>
    <% end %>
    <% @all.each do |all| %>
      <br>
      <% if @user.alvalue != nil %>
        <% checkval = checked.include?(all.id.to_s) ? true : false %>
      <% else %>
        <% checkval = false %>
      <% end %>
      <%= check_box_tag 'alle[all.id - 1][]', all.id, checkval, {} %>
      <%= all.aname %>
    <% end %>
      <br>
  <%= submit_tag "確定" %>
  <% end %>
</div>

app/views/user_pages/allergiesinput.html.erb
<div class="row">
<h1>アレルギー登録完了しました</h1>
<p>表示のみ。登録処理はCD中</p>
<%= @allstr %>
</div>

app/views/user_pages/confirm.html.erb
<h1>確認</h1>

<%= form_for @user, :url => {:controller => "user_pages" } do |f| %>
    名前: <%= @user.name %>
    <%= f.hidden_field :name %>
    <br />
    メールアドレス: <%= @user.email %>
    <%= f.hidden_field :email %>
    <br />
    パスワード: <%= @user.password %>
    <%= f.hidden_field :password %>
    <br />
    <%= f.submit '戻る', name: "back" %>
    <br />
    <%= f.submit '登録'%>
<% end %>

<%= render 'layouts/footer' %>

app/views/user_pages/destroy.html.erb
<div class="row">
  <h1>退会完了</h1>
  <p>楽Laクックを退会しました</p>
</dev>

app/views/user_pages/edit.html.erb
<div class="row">
  <h1>設定</h1>
    <%= link_to 'アレルギー', 'allergies' %>
    <%= link_to 'お気に入りの削除', 'favdeleteselect' %>
    <tb>
    <%= link_to '退会', {:controller => "user_pages" ,:action => "destroy"}, method: :delete, data:{confirm: "本当に退会しますか？"}%>
    </td>
</dev>

app/views/user_pages/favdeleteselect.html.erb
<div class="row">
  <h1>お気に入りの削除</h1>
  <p>削除したいレシピを選択してください</p>
  <% @user.dishes.each do |userfav| %>
    <%= link_to userfav.dishname, :controller => "user_pages" ,:action => "favdelete", :favid => userfav.id %><br>
  <% end %>
</div>

app/views/user_pages/login.html.erb
<h1>UserPages#login</h1>
<p>Find me in app/views/user_pages/login.html.erb</p>
<%= render 'layouts/footer' %>

app/views/user_pages/profile.html.erb
<div class="row">
  <%= @user = User.find(session[:user_id]) %>
  <h1> <%= @user.name %> </h1>
  <p>お気に入りに登録したレシピ</p>
  <% @user.dishes.each do |favdish| %>
    <br>
    <% r_link = 'http://www.rakulacook.com/recipe/' + favdish.id.to_s %>
    <%= link_to favdish.dishname, r_link %>
  <% end %>
  <br>
  <br>
  <%= link_to '設定', edit_user_page_path%>
  <p>Find me in app/views/user_pages/profile.html.erb</p>
  <%= render 'layouts/footer' %>
</div>

app/views/user_pages/regist.html.erb

<h1>会員登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, :url => {:controller => "user_pages", :action => "confirm"} do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "確認", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/user_pages/show.html.erb

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <!-- <%= gravatar_for @user %> -->
        <%= @user.name %>
      </h1>

    </section>
  </aside>
</div>
<%= render 'layouts/footer' %>